version: 1.0.{build}

image: Visual Studio 2017

init:
  - git clone https://github.com/open-quantum-safe/liboqs C:\liboqs
  - msbuild /p:configuration=Debug C:\liboqs\VisualStudio\liboqs.sln /nologo /noconsolelogger
  - msbuild /p:configuration=Release C:\liboqs\VisualStudio\liboqs.sln /nologo /noconsolelogger

configuration:
    - Debug
    - Release

test_script:
    - cmd: >-
        %APPVEYOR_BUILD_FOLDER%\VisualStudio\x64\%CONFIGURATION%\kem

        %APPVEYOR_BUILD_FOLDER%\VisualStudio\x64\%CONFIGURATION%\sig
