version: 1.0.{build}

image: Visual Studio 2017

platform: x64

init:
  - git clone https://github.com/open-quantum-safe/liboqs C:\liboqs
  - msbuild /m /p:configuration=Debug C:\liboqs\VisualStudio\liboqs.sln /nologo /noconsolelogger
  - msbuild /m /p:configuration=Release C:\liboqs\VisualStudio\liboqs.sln /nologo /noconsolelogger

environment:
    LIBOQS_INSTALL_PATH: C:\liboqs
    
build:
    project: VisualStudio/liboqs-cpp.sln
    verbosity: minimal
    parallel: true

configuration:
    - Debug
    - Release

test_script:
    - cmd: >-
        %APPVEYOR_BUILD_FOLDER%\VisualStudio\%PLATFORM%\%CONFIGURATION%\kem

        %APPVEYOR_BUILD_FOLDER%\VisualStudio\%PLATFORM%\%CONFIGURATION%\sig
